apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product-service-v30
  name: product-service-v30
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service-v30
  strategy: {}
  template:
    metadata:
      labels:
        app: product-service-v30
    spec:
      containers:
      - image: 195400145213.dkr.ecr.us-east-1.amazonaws.com/proyecto-ort-im:product-service-v30
        name: product-service-v30
        ports: 
      - containerPort: 80
      volumeMounts:
        - name: persistent-storage
          mountPath: "/var/product-servicemnt"
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: pvc-efs

